document.write('<br /><table width="100%" border="0" cellspacing="0" cellpadding="0" style="border:1px solid #D7D7D7;padding:10px 10px 10px 10px;">');
document.write('  <tr>');
document.write('    <td><table width="100%" border="0" cellspacing="0" cellpadding="0">');
document.write('  <tr>');
document.write('    <td width="214" valign="top"><img src="../lojas/00023005/images/FormLogo.gif" width="159" height="160" border="0" /></td>');
document.write('    <td width="10"><img src="../lojas/00023005/images/Trans.gif" width="10" height="10" border="0" /></td>');
document.write('    <td valign="top"><p align="justify"><span class="VermM_">Form Design Prize</span></p><p align="justify">Desde a década de 1970, o prêmio Form – form aus Handwerk und Industrie (forma do comércio e indústria) é concedido anualmente pelo Bundesverband Kunsthandwerk e.V., durante a Feira Internacional Tendence, em Frankfurt.</p><p align="justify">O concurso evoluiu ao longo dos anos, sendo atualmente um renomado prêmio de design alemão, considerado tanto pelos fabricantes quanto pelos compradores como um selo de aprovação e qualidade para os produtos vencedores.</p><p align="justify">A competição é aberta para todos os expositores da Tendence Fair e os produtos vencedores ficam expostos numa sala especial durante a feira.');
document.write('</p></td>');
document.write('</tr>');
document.write('</table>');
document.write('</td>');
document.write('  </tr>');
document.write('</table><br />');